logging.level:
  org.springframework.security: TRACE

spring:
  security:
    saml2:
      relyingparty:
        registration:
          login-app-saml:
            signing:
              credentials:
                - private-key-location: classpath:credentials/rp-private.key
                  certificate-location: classpath:credentials/rp-certificate.crt
            singlelogout:
              binding: POST
              url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: https://localhost:8443/realms/springBoot/protocol/saml/descriptor

