server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
            scope: openid,profile
            client-name: Spring
          azure:
            provider: azure
            client-id: 0685be9b-239e-408f-ace5-39d00c5c8605
            client-secret: nZW8Q~dIDBGCkUbvWOlivAfWnpI6hzONH97UwcKx
            redirect-uri: http://localhost:8080/login/oauth2/code/azure
            scope:
              - openid
              - email
              - profile
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
#          keycloak:
#            provider: keycloak
#            client-id: login-app
#            scope: openid,profile
#            client-name: Keycloak v20 on localhost:8443
#            client-secret: hDhT8LQYef8ZZsGBMqajptdWLI6jtTLZ
#          keycloak-issuer-only:
#            provider: keycloak-issuer-only
#            client-id: login-app
#            scope: openid,profile
#            client-name: Keycloak v20 on localhost:8443 issuer only
#            client-secret: hDhT8LQYef8ZZsGBMqajptdWLI6jtTLZ
#          keycloak-http:
#            provider: keycloak-http
#            client-id: login-app
#            scope: openid,profile
#            client-name: Keycloak v20 on localhost:8095
#            client-secret: hDhT8LQYef8ZZsGBMqajptdWLI6jtTLZ
        provider:
#          keycloak:
#            issuer-uri: https://localhost:8443/realms/springBoot
#            token-uri: https://localhost:8443/realms/springBoot/protocol/openid-connect/token
#            user-info-uri: https://localhost:8443/realms/springBoot/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#            scope: openid,profile
#          keycloak-issuer-only:
#            issuer-uri: https://localhost:8443/realms/springBoot
#            user-name-attribute: preferred_username
#            scope: openid,profile
#          keycloak-http:
#            issuer-uri: http://localhost:8095/realms/springBoot
#            token-uri: http://localhost:8095/realms/springBoot/protocol/openid-connect/token
#            user-info-uri: http://localhost:8095/realms/springBoot/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#            scope: openid,profile
          spring:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
          azure:
            issuer-uri: https://login.microsoftonline.com/0d09fc44-e019-4be3-a4e4-b1a652e7b32f/v2.0
            ## https://www.baeldung.com/spring-boot-azuerad-authenticate-users:
            ##             issuer-uri: https://login.microsoftonline.com/your-tenant-id-comes-here/v2.0
            #